server:
  port: 6666
accounts:
  datasource:
    url: jdbc:mysql://localhost:3306/kodilla_pro?serverTimezone=Europe/Warsaw&useSSL=False
    username: kodilla_pro
    password: Yc5CJpJ43k*.
    ddl-mode: update